# Generated by Django 4.2 on 2023-04-11 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_message_sender_alter_thread_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="participants",
            field=models.ManyToManyField(
                related_name="threads", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
